name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fileseek
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils libmagic1

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine pytest

      - name: Install package dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: |
          pytest tests/

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 
      
      - name: Create Tag Automatically
        id: create_tag
        run: |
          VERSION="v1.0.0"  # Change this for new releases
          git tag $VERSION
          git push origin $VERSION